const notes = [
  {
    id: 1,
    title: "Shopping List",
    description:"In JSON format, the same list would be written like this",
    inputCode:"<ul id=\"shopping-list\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const shoppingData = {\r\n        \"apples\": 5,\r\n        \"milk\": \"2 liters\",\r\n        \"bread\": \"1 loaf\"\r\n    };\r\n\r\n    \/\/ Access the shopping list UL element\r\n    const listElement = document.getElementById(\'shopping-list\');\r\n\r\n    \/\/ Loop through the JSON data and create list items\r\n    for (const item in shoppingData) {\r\n        if (shoppingData.hasOwnProperty(item)) {\r\n            const listItem = document.createElement(\'li\');\r\n            listItem.textContent = `${item}: ${shoppingData[item]}`;\r\n            listElement.appendChild(listItem);\r\n        }\r\n    }\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>apples: 5<\/li>\r\n    <li>milk: 2 liters<\/li>\r\n    <li>bread: 1 loaf<\/li>\r\n<\/ul>",
  },
  {
    id: 2,
    title: "Objects (Key-Value Pairs)",
    description:"An object in JSON is like a dictionary or a set of labeled data. It stores information in key-value pairs, where each key (name) has a corresponding value.",
    inputCode:"<ul id=\"student-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const studentData = {\r\n        \"name\": \"Alice\",\r\n        \"age\": 14,\r\n        \"class\": \"8th Grade\"\r\n    };\r\n\r\n    \/\/ Access the student info UL element\r\n    const listElement = document.getElementById(\'student-info\');\r\n\r\n    \/\/ Loop through the JSON data and create list items\r\n    for (const key in studentData) {\r\n        if (studentData.hasOwnProperty(key)) {\r\n            const listItem = document.createElement(\'li\');\r\n            listItem.textContent = `${key.charAt(0).toUpperCase() + key.slice(1)}: ${studentData[key]}`;\r\n            listElement.appendChild(listItem);\r\n        }\r\n    }\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Name: Alice<\/li>\r\n    <li>Age: 14<\/li>\r\n    <li>Class: 8th Grade<\/li>\r\n<\/ul>",
  },
  {
    id: 3,
    title: "Objects and Arrays Together",
    description:"JSON objects and arrays can be combined to create more complex structures.",
    inputCode:"<ul id=\"student-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const studentData = {\r\n        \"name\": \"Alice\",\r\n        \"age\": 14,\r\n        \"subjects\": [\r\n            {\r\n                \"subject\": \"Math\",\r\n                \"score\": 95\r\n            },\r\n            {\r\n                \"subject\": \"Science\",\r\n                \"score\": 88\r\n            }\r\n        ]\r\n    };\r\n\r\n    \/\/ Access the student info UL element\r\n    const listElement = document.getElementById(\'student-info\');\r\n\r\n    \/\/ Display the name\r\n    const nameItem = document.createElement(\'li\');\r\n    nameItem.textContent = `Name: ${studentData.name}`;\r\n    listElement.appendChild(nameItem);\r\n\r\n    \/\/ Display the age\r\n    const ageItem = document.createElement(\'li\');\r\n    ageItem.textContent = `Age: ${studentData.age}`;\r\n    listElement.appendChild(ageItem);\r\n\r\n    \/\/ Loop through the subjects array and display each subject and its score\r\n    const subjectsItem = document.createElement(\'li\');\r\n    subjectsItem.textContent = \'Subjects and Scores:\';\r\n    listElement.appendChild(subjectsItem);\r\n\r\n    studentData.subjects.forEach(subject => {\r\n        const subjectItem = document.createElement(\'li\');\r\n        subjectItem.textContent = `${subject.subject}: ${subject.score}`;\r\n        listElement.appendChild(subjectItem);\r\n    });\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Name: Alice<\/li>\r\n    <li>Subjects and Scores:<\/li>\r\n    <li>Math: 95<\/li>\r\n    <li>Age: 14<\/li>\r\n    <li>Science: 88<\/li>\r\n<\/ul>",
  },
  {
    id: 4,
    title: "Objects (Unordered Collection of Name/Value Pairs)",
    description:"An object in JSON is a collection of key-value pairs enclosed in curly braces {}. Each key is a string, and its value can be of different data types.",
    inputCode:"<ul id=\"user-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const userData = {\r\n        \"name\": \"John Doe\",\r\n        \"age\": 30,\r\n        \"isEmployed\": true\r\n    };\r\n\r\n    \/\/ Access the user info UL element\r\n    const listElement = document.getElementById(\'user-info\');\r\n\r\n    \/\/ Display the name\r\n    const nameItem = document.createElement(\'li\');\r\n    nameItem.textContent = `Name: ${userData.name}`;\r\n    listElement.appendChild(nameItem);\r\n\r\n    \/\/ Display the age\r\n    const ageItem = document.createElement(\'li\');\r\n    ageItem.textContent = `Age: ${userData.age}`;\r\n    listElement.appendChild(ageItem);\r\n\r\n    \/\/ Display employment status\r\n    const employmentStatus = userData.isEmployed ? \"Employed\" : \"Unemployed\";\r\n    const employmentItem = document.createElement(\'li\');\r\n    employmentItem.textContent = `Employment Status: ${employmentStatus}`;\r\n    listElement.appendChild(employmentItem);\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Name: John Doe<\/li>\r\n    <li>Age: 30<\/li>\r\n    <li>Employment Status: Employed<\/li>\r\n<\/ul>",
  },
  {
    id: 5,
    title: "Arrays (Ordered Collection of Values)",
    description:"An array is a list of values enclosed in square brackets []. The values inside an array are ordered, meaning their position matters.",
    inputCode:"<ul id=\"fruits-list\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON array\r\n    const fruits = [\"Apple\", \"Banana\", \"Cherry\"];\r\n\r\n    \/\/ Access the fruits list UL element\r\n    const listElement = document.getElementById(\'fruits-list\');\r\n\r\n    \/\/ Loop through the array and create list items\r\n    fruits.forEach(fruit => {\r\n        const listItem = document.createElement(\'li\');\r\n        listItem.textContent = fruit;\r\n        listElement.appendChild(listItem);\r\n    });\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Apple<\/li>\r\n    <li>Banana<\/li>\r\n    <li>Cherry<\/li>\r\n<\/ul>",
  },
  {
    id: 6,
    title: "String (Text in Double Quotes)",
    description:"Used for storing text, like names or messages.",
    inputCode:"<div id=\"greeting-message\"><\/div>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const data = {\r\n        \"greeting\": \"Hello, world!\"\r\n    };\r\n\r\n    \/\/ Access the greeting message div element\r\n    const greetingElement = document.getElementById(\'greeting-message\');\r\n\r\n    \/\/ Display the greeting message\r\n    greetingElement.textContent = data.greeting;\r\n<\/script>",
    outputCode:"<div>Hello, world!<\/div>",
  },
  {
    id: 7,
    title: "Number (Integer or Floating-Point)",
    description:"Used for numerical values, both whole numbers and decimals.",
    inputCode:"<ul id=\"product-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const productData = {\r\n        \"price\": 9.99,\r\n        \"quantity\": 3\r\n    };\r\n\r\n    \/\/ Access the product info UL element\r\n    const listElement = document.getElementById(\'product-info\');\r\n\r\n    \/\/ Display the price\r\n    const priceItem = document.createElement(\'li\');\r\n    priceItem.textContent = `Price: $${productData.price.toFixed(2)}`;\r\n    listElement.appendChild(priceItem);\r\n\r\n    \/\/ Display the quantity\r\n    const quantityItem = document.createElement(\'li\');\r\n    quantityItem.textContent = `Quantity: ${productData.quantity}`;\r\n    listElement.appendChild(quantityItem);\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Price: $9.99<\/li>\r\n    <li>Quantity: 3<\/li>\r\n<\/ul>",
  },
  {
    id: 8,
    title: "Object (Another JSON Object inside a JSON Structure)",
    description:"Objects can be nested within other objects. A person’s contact details inside their profile",
    inputCode:"<ul id=\"contact-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const contactData = {\r\n        \"name\": \"Alice\",\r\n        \"contact\": {\r\n            \"email\": \"alice@example.com\",\r\n            \"phone\": \"555-6789\"\r\n        }\r\n    };\r\n\r\n    \/\/ Access the contact info UL element\r\n    const listElement = document.getElementById(\'contact-info\');\r\n\r\n    \/\/ Display the name\r\n    const nameItem = document.createElement(\'li\');\r\n    nameItem.textContent = `Name: ${contactData.name}`;\r\n    listElement.appendChild(nameItem);\r\n\r\n    \/\/ Display the email\r\n    const emailItem = document.createElement(\'li\');\r\n    emailItem.textContent = `Email: ${contactData.contact.email}`;\r\n    listElement.appendChild(emailItem);\r\n\r\n    \/\/ Display the phone number\r\n    const phoneItem = document.createElement(\'li\');\r\n    phoneItem.textContent = `Phone: ${contactData.contact.phone}`;\r\n    listElement.appendChild(phoneItem);\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Name: Alice<\/li>\r\n    <li>Email: alice@example.com<\/li>\r\n    <li>Phone: 555-6789<\/li>\r\n<\/ul>",
  },
  {
    id: 9,
    title: "Array (A JSON Array Inside a JSON Object)",
    description:"An object can contain arrays too. A student’s list of subjects",
    inputCode:"<ul id=\"bob-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const studentData = {\r\n        \"name\": \"Bob\",\r\n        \"subjects\": [\r\n            \"Math\",\r\n            \"Science\",\r\n            \"English\"\r\n        ]\r\n    };\r\n\r\n    \/\/ Access the student info UL element\r\n    const listElement = document.getElementById(\'bob-info\');\r\n\r\n    \/\/ Display the name\r\n    const nameItem = document.createElement(\'li\');\r\n    nameItem.textContent = `Name: ${studentData.name}`;\r\n    listElement.appendChild(nameItem);\r\n\r\n    \/\/ Display the subjects\r\n    const subjectsItem = document.createElement(\'li\');\r\n    subjectsItem.textContent = `Subjects: ${studentData.subjects.join(\', \')}`;\r\n    listElement.appendChild(subjectsItem);\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Name: Bob<\/li>\r\n    <li>Subjects: Math, Science, English<\/li>\r\n<\/ul>",
  },
  {
    id: 10,
    title: "Boolean (true or false)",
    description:"Used for yes/no or true/false values.",
    inputCode:"<ul id=\"student-status\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const userStatus = {\r\n        \"isStudent\": true\r\n    };\r\n\r\n    \/\/ Access the student status UL element\r\n    const listElement = document.getElementById(\'student-status\');\r\n\r\n    \/\/ Display the status\r\n    const statusItem = document.createElement(\'li\');\r\n    statusItem.textContent = `Is Student: ${userStatus.isStudent ? \"Yes\" : \"No\"}`;\r\n    listElement.appendChild(statusItem);\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Is Student: Yes<\/li>\r\n<\/ul>",
  },
  {
    id: 11,
    title: "null (Represents No Value)",
    description:"Used when there is no value assigned to a key.",
    inputCode:"<ul id=\"middle-name\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const userData = {\r\n        \"middleName\": null\r\n    };\r\n\r\n    \/\/ Access the middle name UL element\r\n    const listElement = document.getElementById(\'middle-name\');\r\n\r\n    \/\/ Check if middleName is null or not\r\n    const middleNameItem = document.createElement(\'li\');\r\n    middleNameItem.textContent = `Middle Name: ${userData.middleName ? userData.middleName : \'N\/A\'}`;\r\n    listElement.appendChild(middleNameItem);\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Middle Name: N\/A<\/li>\r\n<\/ul>",
  },
  {
    id: 12,
    title: "Strings",
    description:"",
    inputCode:"<ul id=\"message-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const data = {\r\n        \"message\": \"Hello \\\"World\\\"!\",\r\n        \"path\": \"C:\\\\Users\\\\John\"\r\n    };\r\n\r\n    \/\/ Access the message info UL element\r\n    const listElement = document.getElementById(\'message-info\');\r\n\r\n    \/\/ Display the message (handling quotes)\r\n    const messageItem = document.createElement(\'li\');\r\n    messageItem.textContent = `Message: ${data.message}`;\r\n    listElement.appendChild(messageItem);\r\n\r\n    \/\/ Display the path (handling backslashes)\r\n    const pathItem = document.createElement(\'li\');\r\n    pathItem.textContent = `Path: ${data.path}`;\r\n    listElement.appendChild(pathItem);\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Message: Hello \"World\"!<\/li>\r\n    <li>Path: C:\\Users\\John<\/li>\r\n<\/ul>  <ul id=\"message-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const data = {\r\n        \"message\": \"Hello \\\"World\\\"!\",\r\n        \"path\": \"C:\\\\Users\\\\John\"\r\n    };\r\n\r\n    \/\/ Access the message info UL element\r\n    const listElement = document.getElementById(\'message-info\');\r\n\r\n    \/\/ Display the message (handling quotes)\r\n    const messageItem = document.createElement(\'li\');\r\n    messageItem.textContent = `Message: ${data.message}`;\r\n    listElement.appendChild(messageItem);\r\n\r\n    \/\/ Display the path (handling backslashes)\r\n    const pathItem = document.createElement(\'li\');\r\n    pathItem.textContent = `Path: ${data.path}`;\r\n    listElement.appendChild(pathItem);\r\n<\/script>",
  },
  {
    id: 13,
    title: "Numbers",
    description:"",
    inputCode:"<ul id=\"number-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const numberData = {\r\n        \"integer\": 42,\r\n        \"float\": 3.14159,\r\n        \"scientific\": 1.23e-4\r\n    };\r\n\r\n    \/\/ Access the number info UL element\r\n    const listElement = document.getElementById(\'number-info\');\r\n\r\n    \/\/ Display the integer\r\n    const integerItem = document.createElement(\'li\');\r\n    integerItem.textContent = `Integer: ${numberData.integer}`;\r\n    listElement.appendChild(integerItem);\r\n\r\n    \/\/ Display the float with a fixed number of decimals\r\n    const floatItem = document.createElement(\'li\');\r\n    floatItem.textContent = `Float: ${numberData.float.toFixed(5)}`;\r\n    listElement.appendChild(floatItem);\r\n\r\n    \/\/ Display the scientific number\r\n    const scientificItem = document.createElement(\'li\');\r\n    scientificItem.textContent = `Scientific: ${numberData.scientific}`;\r\n    listElement.appendChild(scientificItem);\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Integer: 42<\/li>\r\n    <li>Float: 3.14159<\/li>\r\n    <li>Scientific: 0.000123<\/li>\r\n<\/ul>",
  },
  {
    id: 14,
    title: "Nested Structures",
    description:"JSON supports nesting objects and arrays to create complex data structures. You can store arrays inside objects and objects inside arrays",
    inputCode:"<ul id=\"person-info\"><\/ul>\r\n<ul id=\"hobbies-info\"><\/ul>\r\n\r\n<script>\r\n    \/\/ Define the JSON data\r\n    const data = {\r\n        \"person\": {\r\n            \"name\": \"John Doe\",\r\n            \"contact\": {\r\n                \"email\": \"john@example.com\",\r\n                \"phone\": \"555-1234\"\r\n            }\r\n        },\r\n        \"hobbies\": [\r\n            \"reading\",\r\n            \"swimming\",\r\n            {\r\n                \"name\": \"chess\",\r\n                \"level\": \"intermediate\"\r\n            }\r\n        ]\r\n    };\r\n\r\n    \/\/ Access the person info UL element\r\n    const personElement = document.getElementById(\'person-info\');\r\n\r\n    \/\/ Display the person\'s name\r\n    const nameItem = document.createElement(\'li\');\r\n    nameItem.textContent = `Name: ${data.person.name}`;\r\n    personElement.appendChild(nameItem);\r\n\r\n    \/\/ Display the contact details\r\n    const emailItem = document.createElement(\'li\');\r\n    emailItem.textContent = `Email: ${data.person.contact.email}`;\r\n    personElement.appendChild(emailItem);\r\n\r\n    const phoneItem = document.createElement(\'li\');\r\n    phoneItem.textContent = `Phone: ${data.person.contact.phone}`;\r\n    personElement.appendChild(phoneItem);\r\n\r\n    \/\/ Access the hobbies info UL element\r\n    const hobbiesElement = document.getElementById(\'hobbies-info\');\r\n\r\n    \/\/ Loop through the hobbies array\r\n    data.hobbies.forEach(hobby => {\r\n        if (typeof hobby === \'string\') {\r\n            const hobbyItem = document.createElement(\'li\');\r\n            hobbyItem.textContent = `Hobby: ${hobby}`;\r\n            hobbiesElement.appendChild(hobbyItem);\r\n        } else if (typeof hobby === \'object\') {\r\n            const hobbyItem = document.createElement(\'li\');\r\n            hobbyItem.textContent = `Hobby: ${hobby.name} (Level: ${hobby.level})`;\r\n            hobbiesElement.appendChild(hobbyItem);\r\n        }\r\n    });\r\n<\/script>",
    outputCode:"<ul>\r\n    <li>Name: John Doe<\/li>\r\n    <li>Email: john@example.com<\/li>\r\n    <li>Phone: 555-1234<\/li>\r\n<\/ul>\r\n\r\n<ul>\r\n    <li>Hobby: reading<\/li>\r\n    <li>Hobby: swimming<\/li>\r\n    <li>Hobby: chess (Level: intermediate)<\/li>\r\n<\/ul>",
  },
  {
    id: 15,
    title: "JavaScript",
    description:"Since JSON is derived from JavaScript, it's very easy to work with in JS.",
    inputCode:"<p><strong>Original JSON String:<\/strong><\/p>\r\n<pre id=\"json-string\"><\/pre>\r\n\r\n<p><strong>Parsed Object:<\/strong><\/p>\r\n<pre id=\"parsed-object\"><\/pre>\r\n\r\n<p><strong>Formatted JSON String:<\/strong><\/p>\r\n<pre id=\"formatted-json\"><\/pre>\r\n\r\n<script>\r\n    \/\/ Original JSON string\r\n    const jsonString = \'{\"name\":\"John\",\"age\":30}\';\r\n\r\n    \/\/ Parse JSON string to JavaScript object\r\n    const obj = JSON.parse(jsonString);\r\n\r\n    \/\/ Display the original JSON string\r\n    document.getElementById(\'json-string\').textContent = jsonString;\r\n\r\n    \/\/ Display the parsed JavaScript object\r\n    document.getElementById(\'parsed-object\').textContent = `Name: ${obj.name}, Age: ${obj.age}`;\r\n\r\n    \/\/ Convert JavaScript object back to JSON string with indentation\r\n    const formattedJsonString = JSON.stringify(obj, null, 2); \/\/ 2 spaces for indentation\r\n\r\n    \/\/ Display the formatted JSON string\r\n    document.getElementById(\'formatted-json\').textContent = formattedJsonString;\r\n\r\n    \/\/ Log to console for demonstration\r\n    console.log(obj.name); \/\/ Output: John\r\n    console.log(obj.age);  \/\/ Output: 30\r\n    console.log(formattedJsonString);\r\n<\/script>",
    outputCode:"<p><strong>Original JSON String:<\/strong><\/p>\r\n<pre id=\"json-string\">{\"name\":\"John\",\"age\":30}<\/pre>\r\n\r\n<p><strong>Parsed Object:<\/strong><\/p>\r\n<pre id=\"parsed-object\">Name: John, Age: 30<\/pre>\r\n\r\n<p><strong>Formatted JSON String:<\/strong><\/p>\r\n<pre id=\"formatted-json\">{\"name\": \"John\",\"age\": 30}<\/pre>",
  },
  {
    id: 16,
    title: "Python",
    description:"Python provides the built-in json module for handling JSON.",
    inputCode:"import json\r\n\r\n# Parse JSON string to Python object\r\nobj = json.loads(\'{\"name\":\"John\",\"age\":30}\')\r\nprint(obj[\"name\"])  # Output: John\r\nprint(obj[\"age\"])   # Output: 30\r\n\r\n# Convert Python object to JSON string with 2 spaces for indentation\r\njson_string = json.dumps(obj, indent=2)\r\nprint(json_string)",
    outputCode:"<p>John<\/p>\r\n<pre id=\"json-string\">\r\n30\r\n{\r\n  \"name\": \"John\",\r\n  \"age\": 30\r\n}\r\n<\/pre>",
  },
  {
    id: 17,
    title: "Java",
    description:"Java doesn’t have built-in JSON support, but libraries like org.json, Gson, and Jackson are commonly used.",
    inputCode:"import org.json.JSONObject;\r\n\r\npublic class Main {\r\n    public static void main(String[] args) {\r\n        \/\/ Create a JSON object\r\n        JSONObject obj = new JSONObject();\r\n        obj.put(\"name\", \"John\");\r\n        obj.put(\"age\", 30);\r\n\r\n        \/\/ Convert to string\r\n        String jsonString = obj.toString();\r\n        \r\n        \/\/ Print the JSON string\r\n        System.out.println(jsonString);\r\n    }\r\n}",
    outputCode:"<pre>{\"name\":\"John\",\"age\":30}<\/pre>",
  }
];

window.notes = notes; 