const notes = [
  {
    id: 1,
    title: "Generic Container",
    description:"A <div> is a block-level container used for grouping elements.",
    inputCode:'<div style="background-color: lightblue; padding: 10px;">\r\n  <p>This is inside a div.</p>\r\n</div>',
    outputCode:'<div style="background-color: lightblue; color: black; padding: 10px;">\r\n  <p>This is inside a div.</p>\r\n</div>',
  },
  {
    id: 2,
    title: "Headings",
    description:"Headings define different levels of importance, with <h1> being the most important and <h6> the least.",
    inputCode:"<h1>Main Heading</h1>\r\n<h2>Subheading</h2>\r\n<h3>Section Title</h3>\r\n<h4>Subsection</h4>\r\n<h5>Smaller Section</h5>\r\n<h6>Least Important Heading</h6>",
    outputCode:"<h1>Main Heading</h1>\r\n<h2>Subheading</h2>\r\n<h3>Section Title</h3>\r\n<h4>Subsection</h4>\r\n<h5>Smaller Section</h5>\r\n<h6>Least Important Heading</h6>",
  },
  {
    id: 3,
    title: "Paragraphs",
    description:"A <p> tag is used for text content. It creates a new line before and after the paragraph.",
    inputCode:"<p>This is a paragraph of text.</p>\r\n<p>Each paragraph starts on a new line.</p>",
    outputCode:"<p>This is a paragraph of text.</p>\r\n<p>Each paragraph starts on a new line.</p>",
  },
  {
    id: 4,
    title: "Lists",
    description:"<ul> (Unordered List) creates bulleted lists. <ol> (Ordered List) creates numbered lists.",
    inputCode:"<ul>\r\n  <li>Item 1</li>\r\n  <li>Item 2</li>\r\n  <li>Item 3</li>\r\n</ul>\r\n\r\n\r\n<ol>\r\n  <li>First item</li>\r\n  <li>Second item</li>\r\n  <li>Third item</li>\r\n</ol>",
    outputCode:"<ul>\r\n  <li>Item 1</li>\r\n  <li>Item 2</li>\r\n  <li>Item 3</li>\r\n</ul>\r\n\r\n\r\n<ol>\r\n  <li>First item</li>\r\n  <li>Second item</li>\r\n  <li>Third item</li>\r\n</ol>",
  },
  {
    id: 5,
    title: "Table",
    description: "Tables organize data into rows and columns.",
    inputCode:'<table border="1">\r\n  <tr>\r\n      <th>Name</th>\r\n      <th>Age</th>\r\n  </tr>\r\n  <tr>\r\n      <td>Alice</td>\r\n      <td>25</td>\r\n  </tr>\r\n  <tr>\r\n      <td>Bob</td>\r\n      <td>30</td>\r\n  </tr>\r\n</table>',
    outputCode:'<table border="1">\r\n  <tr>\r\n      <th>Name</th>\r\n      <th>Age</th>\r\n  </tr>\r\n  <tr>\r\n      <td>Alice</td>\r\n      <td>25</td>\r\n  </tr>\r\n  <tr>\r\n      <td>Bob</td>\r\n      <td>30</td>\r\n  </tr>\r\n</table>',
  },
  {
    id: 6,
    title: "Forms",
    description: "The <form> element is used for user input.",
    inputCode:'<form action="/submit" method="post" autocomplete="on">\r\n  <label for="name">Name:</label>\r\n  <input type="text" id="name" name="name" autocomplete="name" />\r\n  <input type="submit" value="Submit" />\r\n</form>',
    outputCode:'<form action="/submit" method="post" autocomplete="on">\r\n  <label for="name">Name:</label>\r\n  <input type="text" id="name" name="name" autocomplete="name" />\r\n  <input type="submit" value="Submit" />\r\n</form>',
  },
  {
    id: 7,
    title: "Semantic Block-Level Elements",
    description:"HTML5 introduced semantic elements that improve readability and SEO. It provides meaningful elements that clearly describe their content and role in a webpage.",
    inputCode:'<header>\r\n  <h1>Welcome to My Website</h1>\r\n</header>\r\n\r\n\r\n<nav>\r\n  <ul>\r\n      <li><a href="#">Home</a></li>\r\n      <li><a href="#">About</a></li>\r\n      <li><a href="#">Contact</a></li>\r\n  </ul>\r\n</nav>\r\n\r\n\r\n<section>\r\n  <h2>About Us</h2>\r\n  <p>We provide high-quality services. </p>\r\n</section>\r\n\r\n\r\n<article>\r\n  <h3>Latest News</h3>\r\n  <p>Check out our latest updates. </p>\r\n</article>\r\n\r\n\r\n<aside>\r\n  <h3>Sidebar Content</h3>\r\n  <p>Links to additional resources.</p>\r\n</aside>\r\n\r\n\r\n<footer>\r\n  <p>&copy; 2025 My Website</p>\r\n</footer>',
    outputCode:'<header>\r\n  <h1>Welcome to My Website</h1>\r\n</header>\r\n\r\n\r\n<nav>\r\n  <ul>\r\n      <li><a href="#">Home</a></li>\r\n      <li><a href="#">About</a></li>\r\n      <li><a href="#">Contact</a></li>\r\n  </ul>\r\n</nav>\r\n\r\n\r\n<section>\r\n  <h2>About Us</h2>\r\n  <p>We provide high-quality services. </p>\r\n</section>\r\n\r\n\r\n<article>\r\n  <h3>Latest News</h3>\r\n  <p>Check out our latest updates. </p>\r\n</article>\r\n\r\n\r\n<aside>\r\n  <h3>Sidebar Content</h3>\r\n  <p>Links to additional resources.</p>\r\n</aside>\r\n\r\n\r\n<footer>\r\n  <p>&copy; 2025 My Website</p>\r\n</footer>',
  },
  {
    id: 8,
    title: "Generic Inline Container",
    description:"The <span> element is used to group text or elements for styling without affecting layout.",
    inputCode:'<p>This is a <span style="color: red;">highlighted</span> word.</p>',
    outputCode:'<p>This is a <span style="color: red;">highlighted</span> word.</p>',
  },
  {
    id: 9,
    title: "Anchor (Hyperlink)",
    description:
      "The <a> element creates clickable links to other pages, sections, or external sites.",
    inputCode:'<p>Visit <a href="https://example.com">Example Website</a> for more details.</p>',
    outputCode:'<p>Visit <a href="https://example.com">Example Website</a> for more details.</p>',
  },
  {
    id: 10,
    title: "Image",
    description: "The <img> element embeds an image in a webpage.",
    inputCode:'<img src="https://picsum.photos/300" alt="A beautiful landscape" width="300">',
    outputCode:'<img src="https://picsum.photos/300" alt="A beautiful landscape" width="300">',
  },
  {
    id: 11,
    title: "Text Emphasis",
    description:"<em>: Emphasized text (usually italicized) <strong>: Important text (usually bold)",
    inputCode:"<p>This is <em>important</em> information.</p>\r\n<p>This is <strong>very important</strong> information.</p>",
    outputCode:"<p>This is <em>important</em> information.</p>\r\n<p>This is <strong>very important</strong> information.</p>",
  },
  {
    id: 12,
    title: "Code Snippet",
    description:"The <code> element is used to display programming code in a monospaced font.",
    inputCode:'<p>To print in Python, use <code>print("Hello, World!")</code>.</p>',
    outputCode:'<p>To print in Python, use <code>print("Hello, World!")</code>.</p>',
  },
  {
    id: 13,
    title: "Bold & Italic Text (Non-Semantic)",
    description:"<b>: Bold text (without importance) <i>: Italic text (without emphasis)",
    inputCode:"<p>This is <b>bold</b> text.</p>\r\n<p>This is <i>italic</i> text.</p>",
    outputCode:"<p>This is <b>bold</b> text.</p>\r\n<p>This is <i>italic</i> text.</p>",
  },
  {
    id: 14,
    title: "Common Attributes",
    description:'id - unique identifier E.g.: <p id="intro">Welcome to my website!</p> \r\nclass - classifies elements (for CSS/JS) E.g.: <p class="highlight">This is highlighted text.</p> \r\nstyle - inline CSS styles E.g.: <p style="color: green; font-size: 20px;">This is inline-styled text.</p> \r\ntitle - tooltip text E.g.: <a href="https://example.com" title="Go to Example Website">Visit Example</a> \r\nlang \u2013 language E.g.: <html lang="en"> <p lang="fr">Bonjour! (Hello in French)</p> \r\ndata-* - custom data attributes \r\nStores custom data inside an element for JavaScript processing. \r\nCan be used to pass extra information without affecting design. ',
    inputCode:"<button data-userid=\"123\">Click Me</button>\r\n\r\n<script>\r\n  const buttons = document.querySelectorAll('button[data-userid]');\r\n  buttons.forEach(button => {\r\n    button.addEventListener('click', () => {\r\n      console.log('User ID:', button.dataset.userid);\r\n    });\r\n  });\r\n</script>",
    outputCode: '<button data-userid="123">Click Me</button>',
  },
  {
    id: 15,
    title: "Text Formatting Tags",
    description: "",
    inputCode:'<b>Bold text</b>\r\n<strong>Important text</strong>\r\n<i>Italic text</i>\r\n<em>Emphasized text</em>\r\n<mark>Marked/highlighted text</mark>\r\n<small>Small text</small>\r\n<del>Deleted text</del>\r\n<ins>Inserted text</ins>\r\n<sub>Subscript text</sub>\r\n<sup>Superscript text</sup>\r\n<code>Computer code</code>\r\n<kbd>Keyboard input</kbd>\r\n<pre>Preformatted text</pre>\r\n<blockquote>Blockquote</blockquote>\r\n<q>Short quotation</q>\r\n<abbr title="HyperText Markup Language">HTML</abbr>\r\n<address>Contact information</address>\r\n<cite>Work title</cite>\r\n<bdo dir="rtl">Text direction</bdo>',
    outputCode:'<b>Bold text</b>\r\n<strong>Important text</strong>\r\n<i>Italic text</i>\r\n<em>Emphasized text</em>\r\n<mark>Marked/highlighted text</mark>\r\n<small>Small text</small>\r\n<del>Deleted text</del>\r\n<ins>Inserted text</ins>\r\n<sub>Subscript text</sub>\r\n<sup>Superscript text</sup>\r\n<code>Computer code</code>\r\n<kbd>Keyboard input</kbd>\r\n<pre>Preformatted text</pre>\r\n<blockquote>Blockquote</blockquote>\r\n<q>Short quotation</q>\r\n<abbr title="HyperText Markup Language">HTML</abbr>\r\n<address>Contact information</address>\r\n<cite>Work title</cite>\r\n<bdo dir="rtl">Text direction</bdo>',
  },
  {
    id: 16,
    title: "Basic Link",
    description: "",
    inputCode: '<a href="https://www.example.com">Link text</a>',
    outputCode: '<a href="https://www.example.com">Link text</a>',
  },
  {
    id: 17,
    title: "Link to Email",
    description: "",
    inputCode: '<a href="mailto:example@example.com">Send email</a>',
    outputCode: '<a href="mailto:example@example.com">Send email</a>',
  },
  {
    id: 18,
    title: "Link to Phone",
    description: "",
    inputCode: '<a href="tel:+1234567890">Call us</a>',
    outputCode: '<a href="tel:+1234567890">Call us</a>',
  },
  {
    id: 19,
    title: "Link Attributes",
    description: "",
    inputCode:'<a href="page.html" target="_blank" rel="noopener noreferrer">Opens in new tab</a>',
    outputCode:'<a href="page.html" target="_blank" rel="noopener noreferrer">Opens in new tab</a>',
  },
  {
    id: 20,
    title: "Bookmark Links",
    description:"A bookmark in HTML allows users to quickly jump to a specific section within the same webpage. It is useful for long pages where you want to provide easy navigation.",
    inputCode:
      '<!-- Link to bookmark -->\r\n<a href="#section1">Go to Section 1</a>\r\n\r\n\r\n<!-- The bookmark target -->\r\n<h2 id="section1">Section 1</h2>',
    outputCode:'<!-- Link to bookmark -->\r\n<a href="#section1">Go to Section 1</a>\r\n\r\n\r\n<!-- The bookmark target -->\r\n<h2 id="section1">Section 1</h2>',
  },
  {
    id: 21,
    title: "Basic Image",
    description: "",
    inputCode:'<img src="https://picsum.photos/300/200" alt="A beautiful landscape">',
    outputCode:'<img src="https://picsum.photos/300/200" alt="A beautiful landscape">',
  },
  {
    id: 22,
    title: "Image with Size",
    description: "",
    inputCode:'<img src="https://picsum.photos/500/300" alt="Nature landscape" width="500" height="300">',
    outputCode:'<img src="https://picsum.photos/500/300" alt="Nature landscape" width="500" height="300">',
  },
  {
    id: 23,
    title: "Responsive Image",
    description: "",
    inputCode:'<img src="https://loremflickr.com/600/400/mountains" alt="Mountain landscape" style="max-width:100%; height:auto;">',
    outputCode:'<img src="https://loremflickr.com/600/400/mountains" alt="Mountain landscape" style="max-width:100%; height:auto;">',
  },
  {
    id: 24,
    title: "Image Maps",
    description: "",
    inputCode:'<img src="https://picsum.photos/id/1025/600/400" alt="Workplace" usemap="#workmap">\r\n\r\n<map name="workmap">\r\n  <area shape="rect" coords="34,44,270,350" alt="Computer" href="computer.htm">\r\n  <area shape="rect" coords="290,172,333,250" alt="Phone" href="phone.htm">\r\n  <area shape="circle" coords="337,300,44" alt="Cup" href="coffee.htm">\r\n</map>',
    outputCode:'<img src="https://picsum.photos/id/1025/600/400" alt="Workplace" usemap="#workmap">\r\n\r\n<map name="workmap">\r\n  <area shape="rect" coords="34,44,270,350" alt="Computer" href="computer.htm">\r\n  <area shape="rect" coords="290,172,333,250" alt="Phone" href="phone.htm">\r\n  <area shape="circle" coords="337,300,44" alt="Cup" href="coffee.htm">\r\n</map>',
  },
  {
    id: 25,
    title: "Figure with Caption",
    description: "",
    inputCode:'<figure>\r\n  <img src="https://source.unsplash.com/300x200/?city,night" alt="City at night">\r\n  <figcaption>City lights glowing at night</figcaption>\r\n</figure>',
    outputCode:'<figure>\r\n    <img src="https://picsum.photos/300/200?random=1" alt="Random image">\r\n    <figcaption>Random image</figcaption>\r\n</figure>',
  },
  {
    id: 26,
    title: "Unordered List",
    description: "",
    inputCode:"<ul>\r\n  <li>Item 1</li>\r\n  <li>Item 2</li>\r\n  <li>Item 3</li>\r\n</ul>",
    outputCode:"<ul>\r\n  <li>Item 1</li>\r\n  <li>Item 2</li>\r\n  <li>Item 3</li>\r\n</ul>",
  },
  {
    id: 27,
    title: "Ordered List",
    description: "",
    inputCode:"<ol>\r\n  <li>First item</li>\r\n  <li>Second item</li>\r\n  <li>Third item</li>\r\n</ol>",
    outputCode:"<ol>\r\n  <li>First item</li>\r\n  <li>Second item</li>\r\n  <li>Third item</li>\r\n</ol>",
  },
  {
    id: 28,
    title: "Ordered List Types",
    description: "",
    inputCode:'<h2>Default Numbers (1, 2, 3...)</h2>\r\n<ol type="1">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Reversed Numbers</h2>\r\n<ol type="1" reversed>\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Uppercase Letters (A, B, C...)</h2>\r\n<ol type="A">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Lowercase Letters (a, b, c...)</h2>\r\n<ol type="a">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Uppercase Roman Numerals (I, II, III...)</h2>\r\n<ol type="I">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Lowercase Roman Numerals (i, ii, iii...)</h2>\r\n<ol type="i">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>',
    outputCode:'<h2>Default Numbers (1, 2, 3...)</h2>\r\n<ol type="1">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Reversed Numbers</h2>\r\n<ol type="1" reversed>\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Uppercase Letters (A, B, C...)</h2>\r\n<ol type="A">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Lowercase Letters (a, b, c...)</h2>\r\n<ol type="a">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Uppercase Roman Numerals (I, II, III...)</h2>\r\n<ol type="I">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>\r\n\r\n<h2>Lowercase Roman Numerals (i, ii, iii...)</h2>\r\n<ol type="i">\r\n  <li>Item One</li>\r\n  <li>Item Two</li>\r\n  <li>Item Three</li>\r\n</ol>',
  },
  {
    id: 29,
    title: "Description List",
    description: "",
    inputCode:
      "<dl>   //definition list\r\n  <dt>Term 1</dt> //term\r\n  <dd>Definition 1</dd> //definition of the term\r\n  <dt>Term 2</dt>\r\n  <dd>Definition 2</dd>\r\n</dl>",
    outputCode:
      "<dl>   //definition list\r\n  <dt>Term 1</dt> //term\r\n  <dd>Definition 1</dd> //definition of the term\r\n  <dt>Term 2</dt>\r\n  <dd>Definition 2</dd>\r\n</dl>",
  },
  {
    id: 30,
    title: "Nested Lists",
    description: "",
    inputCode:"<ul>\r\n  <li>Item 1</li>\r\n  <li>Item 2</li>\r\n    <ul>\r\n      <li>Subitem 2.1</li>\r\n      <li>Subitem 2.2</li>\r\n    </ul>\r\n  </li>\r\n  <li>Item 3</li>\r\n</ul>",
    outputCode:"<ul>\r\n  <li>Item 1</li>\r\n  <li>Item 2</li>\r\n    <ul>\r\n      <li>Subitem 2.1</li>\r\n      <li>Subitem 2.2</li>\r\n    </ul>\r\n  </li>\r\n  <li>Item 3</li>\r\n</ul>",
  },
  {
    id: 31,
    title: "Basic Table",
    description: "",
    inputCode:'<table border="1">\r\n    <tr> //row\r\n      <th>Header 1</th> //header\r\n      <th>Header 2</th>\r\n    </tr>\r\n    <tr>\r\n      <td>Row 1, Cell 1</td> //data cell\r\n      <td>Row 1, Cell 2</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Row 2, Cell 1</td>\r\n      <td>Row 2, Cell 2</td>\r\n    </tr>\r\n</table>',
    outputCode:'<table border="1">\r\n    <tr> //row\r\n      <th>Header 1</th> //header\r\n      <th>Header 2</th>\r\n    </tr>\r\n    <tr>\r\n      <td>Row 1, Cell 1</td> //data cell\r\n      <td>Row 1, Cell 2</td>\r\n    </tr>\r\n    <tr>\r\n      <td>Row 2, Cell 1</td>\r\n      <td>Row 2, Cell 2</td>\r\n    </tr>\r\n</table>',
  },
  {
    id: 32,
    title: "Table with Caption and Structure",
    description: "",
    inputCode:'<table border="1">\r\n    <caption>Table Caption</caption>\r\n    <thead>\r\n      <tr>\r\n        <th>Header 1</th>\r\n        <th>Header 2</th>\r\n      </tr>\r\n    </thead>\r\n    <tbody>\r\n      <tr>\r\n        <td>Data 1</td>\r\n        <td>Data 2</td>\r\n      </tr>\r\n    </tbody>\r\n    <tfoot>\r\n      <tr>\r\n        <td>Footer 1</td>\r\n        <td>Footer 2</td>\r\n      </tr>\r\n    </tfoot>\r\n</table>',
    outputCode:'<table border="1">\r\n    <caption>Table Caption</caption>\r\n    <thead>\r\n      <tr>\r\n        <th>Header 1</th>\r\n        <th>Header 2</th>\r\n      </tr>\r\n    </thead>\r\n    <tbody>\r\n      <tr>\r\n        <td>Data 1</td>\r\n        <td>Data 2</td>\r\n      </tr>\r\n    </tbody>\r\n    <tfoot>\r\n      <tr>\r\n        <td>Footer 1</td>\r\n        <td>Footer 2</td>\r\n      </tr>\r\n    </tfoot>\r\n</table>',
  },
  {
    id: 33,
    title: "Spanning Columns and Rows",
    description: "",
    inputCode:
      '<table border="1">\r\n    <tr>\r\n      <th>Name</th>\r\n      <th colspan="2">Telephone</th>\r\n    </tr>\r\n    <tr>\r\n      <td>John Doe</td>\r\n      <td>555-1234</td>\r\n      <td>555-5678</td>\r\n    </tr>\r\n    <tr>\r\n      <td rowspan="2">Address</td>\r\n      <td>123 Main St</td>\r\n      <td>Apt 4B</td>\r\n    </tr>\r\n    <tr>\r\n      <td>New York</td>\r\n      <td>NY</td>\r\n    </tr>\r\n</table>',
    outputCode:
      '<table border="1">\r\n    <tr>\r\n      <th>Name</th>\r\n      <th colspan="2">Telephone</th>\r\n    </tr>\r\n    <tr>\r\n      <td>John Doe</td>\r\n      <td>555-1234</td>\r\n      <td>555-5678</td>\r\n    </tr>\r\n    <tr>\r\n      <td rowspan="2">Address</td>\r\n      <td>123 Main St</td>\r\n      <td>Apt 4B</td>\r\n    </tr>\r\n    <tr>\r\n      <td>New York</td>\r\n      <td>NY</td>\r\n    </tr>\r\n</table>',
  },
  {
    id: 34,
    title: "Basic Form",
    description: "",
    inputCode:'<form action="/submit-form" method="post">\r\n  <label for="name">Name:</label>\r\n  <input type="text" id="name" name="name" autocomplete="name"><br>\r\n\r\n  <label for="email">Email:</label>\r\n  <input type="email" id="email" name="email" autocomplete="email"><br>\r\n\r\n  <input type="submit" value="Submit">\r\n</form>',
    outputCode:'<form action="/submit-form" method="post">\r\n  <label for="name">Name:</label>\r\n  <input type="text" id="name" name="name" autocomplete="name"><br>\r\n\r\n  <label for="email">Email:</label>\r\n  <input type="email" id="email" name="email" autocomplete="email"><br>\r\n\r\n  <input type="submit" value="Submit">\r\n</form>',
  },
  {
    id: 35,
    title: "Input Types",
    description: "",
    inputCode:'<input type="text">        <!-- Single-line text input -->\r\n<input type="password">    <!-- Password field -->\r\n<input type="email">       <!-- Email input -->\r\n<input type="number">      <!-- Numeric input -->\r\n<input type="tel">         <!-- Telephone number -->\r\n<input type="url">         <!-- URL input -->\r\n<input type="search">      <!-- Search field -->\r\n<input type="date">        <!-- Date picker -->\r\n<input type="time">        <!-- Time picker -->\r\n<input type="datetime-local"> <!-- Date and time picker -->\r\n<input type="month">       <!-- Month picker -->\r\n<input type="week">        <!-- Week picker -->\r\n<input type="color">       <!-- Color picker -->\r\n<input type="range">       <!-- Range slider -->\r\n<input type="file">        <!-- File upload -->\r\n<input type="checkbox">    <!-- Checkbox -->\r\n<input type="radio">       <!-- Radio button -->\r\n<input type="hidden">      <!-- Hidden field -->\r\n<input type="submit">      <!-- Submit button -->\r\n<input type="reset">       <!-- Reset button -->\r\n<input type="button">      <!-- Generic button -->\r\n<input type="image">       <!-- Image button -->',
    outputCode:'<input type="text" id="text" name="text">             <!-- Single-line text input -->\r\n<input type="password" id="password" name="password"> <!-- Password field -->\r\n<input type="email" id="email" name="email">          <!-- Email input -->\r\n<input type="number" id="number" name="number">       <!-- Numeric input -->\r\n<input type="tel" id="tel" name="tel">                <!-- Telephone number -->\r\n<input type="url" id="url" name="url">                <!-- URL input -->\r\n<input type="search" id="search" name="search">       <!-- Search field -->\r\n<input type="date" id="date" name="date">             <!-- Date picker -->\r\n<input type="time" id="time" name="time">             <!-- Time picker -->\r\n<input type="datetime-local" id="datetime" name="datetime"> <!-- Date and time picker -->\r\n<input type="month" id="month" name="month">          <!-- Month picker -->\r\n<input type="week" id="week" name="week">             <!-- Week picker -->\r\n<input type="color" id="color" name="color">          <!-- Color picker -->\r\n<input type="range" id="range" name="range">          <!-- Range slider -->\r\n<input type="file" id="file" name="file">             <!-- File upload -->\r\n<input type="checkbox" id="subscribe" name="subscribe"> <!-- Checkbox -->\r\n<input type="radio" id="gender" name="gender" value="male"> <!-- Radio button -->\r\n<input type="hidden" name="hiddenField" value="value">    <!-- Hidden field -->\r\n<input type="submit" value="Submit">                  <!-- Submit button -->\r\n<input type="reset" value="Reset">                    <!-- Reset button -->\r\n<input type="button" value="Click Me">                <!-- Generic button -->\r\n<input type="image" src="https://picsum.photos/200" alt="Submit" width="100" height="100" name="imageButton"> <!-- Image button -->',
  },
  {
    id: 36,
    title: "Text Area",
    description: "",
    inputCode:'<textarea name="message" rows="10" cols="30" autocomplete="on">\r\n  Default text\r\n</textarea>',
    outputCode:'<textarea name="message" rows="10" cols="30" autocomplete="on">\r\n  Default text\r\n</textarea>',
  },
  {
    id: 37,
    title: "Select Dropdown",
    description: "",
    inputCode:'<select name="cars">\r\n  <option value="volvo">Volvo</option>\r\n  <option value="saab">Saab</option>\r\n  <option value="mercedes">Mercedes</option>\r\n  <option value="audi">Audi</option>\r\n</select>',
    outputCode:'<select name="cars">\r\n  <option value="volvo">Volvo</option>\r\n  <option value="saab">Saab</option>\r\n  <option value="mercedes">Mercedes</option>\r\n  <option value="audi">Audi</option>\r\n</select>',
  },
  {
    id: 38,
    title: "Select with Option Groups",
    description: "",
    inputCode:'<select name="cars">\r\n  <optgroup label="Swedish Cars">\r\n    <option value="volvo">Volvo</option>\r\n    <option value="saab">Saab</option>\r\n  </optgroup>\r\n  <optgroup label="German Cars">\r\n    <option value="mercedes">Mercedes</option>\r\n    <option value="audi">Audi</option>\r\n  </optgroup>\r\n</select>',
    outputCode:'<select name="cars">\r\n  <optgroup label="Swedish Cars">\r\n    <option value="volvo">Volvo</option>\r\n    <option value="saab">Saab</option>\r\n  </optgroup>\r\n  <optgroup label="German Cars">\r\n    <option value="mercedes">Mercedes</option>\r\n    <option value="audi">Audi</option>\r\n  </optgroup>\r\n</select>',
  },
  {
    id: 39,
    title: "Datalist",
    description: "user can type their own value if it's not in the list.",
    inputCode:'<input list="browsers" name="browser">\r\n<datalist id="browsers">\r\n  <option value="Chrome">\r\n  <option value="Firefox">\r\n  <option value="Safari">\r\n  <option value="Edge">\r\n  <option value="Opera">\r\n</datalist>',
    outputCode:'<input list="browsers" name="browser">\r\n<datalist id="browsers">\r\n  <option value="Chrome">\r\n  <option value="Firefox">\r\n  <option value="Safari">\r\n  <option value="Edge">\r\n  <option value="Opera">\r\n</datalist>',
  },
  {
    id: 40,
    title: "Fieldset and Legend",
    description: "",
    inputCode:'<fieldset>\r\n  <legend>Personal Information:</legend>\r\n  <label for="fname">First name:</label>\r\n  <input type="text" id="fname" name="fname"><br>\r\n  <label for="lname">Last name:</label>\r\n  <input type="text" id="lname" name="lname"><br>\r\n</fieldset>',
    outputCode:'<fieldset>\r\n  <legend>Personal Information:</legend>\r\n  <label for="fname">First name:</label>\r\n  <input type="text" id="fname" name="fname"><br>\r\n  <label for="lname">Last name:</label>\r\n  <input type="text" id="lname" name="lname"><br>\r\n</fieldset>',
  },
  {
    id: 41,
    title: "Value",
    description:
      "Sets an initial value in the input field Use: Pre-fill known information (e.g., user name)",
    inputCode:'<input type="text" id="fullname" name="fullname" value="John Doe">',
    outputCode:'<input type="text" id="fullname" name="fullname" value="John Doe">',
  },
  {
    id: 42,
    title: "Readonly",
    description:
      "Makes the input field non-editable but visible Use: When you want to show data but not allow editing",
    inputCode:'<input type="text" id="readonlyText" name="readonlyText" value="Read Only Text" readonly>',
    outputCode:'<input type="text" id="readonlyText" name="readonlyText" value="Read Only Text" readonly>',
  },
  {
    id: 43,
    title: "Disabled",
    description:
      "Disables the input field (grayed out, can't edit or submit) Use: Temporarily disable inputs based on conditions",
    inputCode:'<input type="text" value="Disabled Field" disabled name="disabledField">',
    outputCode:'<input type="text" value="Disabled Field" disabled name="disabledField">',
  },
  {
    id: 44,
    title: "Size",
    description:"Sets the width of the input in number of characters Use: To control the visible width of the input box",
    inputCode:'<input type="text" size="30" name="sizedField">',
    outputCode:'<input type="text" size="30" name="sizedField">',
  },
  {
    id: 45,
    title: "Maxlength",
    description:"Limits the maximum number of characters Use: To restrict input length (like phone number, username)",
    inputCode: '<input type="text" maxlength="10" name="limitedText">',
    outputCode: '<input type="text" maxlength="10" name="limitedText">',
  },
  {
    id: 46,
    title: "min & max",
    description:"Define minimum and maximum values (mainly for number/date) Use: For numeric ranges (age, quantity, etc.)",
    inputCode: '<input type="number" min="1" max="100" name="numberInput">',
    outputCode: '<input type="number" min="1" max="100" name="numberInput">',
  },
  {
    id: 47,
    title: "Pattern",
    description:"Regular expression pattern for validation Use: For custom format validation (e.g., only letters, specific structure)",
    inputCode:'<input type="text" pattern="[A-Za-z]{3,}" title="Only letters, minimum 3" name="letterOnly">',
    outputCode:'<input type="text" pattern="[A-Za-z]{3,}" title="Only letters, minimum 3" name="letterOnly">',
  },
  {
    id: 48,
    title: "Required",
    description:
      "Makes the input mandatory Use: When input is compulsory to submit the form",
    inputCode: '<input type="email" required name="emailRequired">',
    outputCode: '<input type="email" required name="emailRequired">',
  },
  {
    id: 49,
    title: "Placeholder",
    description:"Shows a hint inside the input Use: To give a short instruction",
    inputCode:'<input type="text" placeholder="Enter your name" name="nameField">',
    outputCode:'<input type="text" placeholder="Enter your name" name="nameField">',
  },
  {
    id: 50,
    title: "Autofocus",
    description:"Automatically focuses this field when the page loads Use: To highlight the first input field for the user",
    inputCode: '<input type="text" autofocus name="autofocusField">',
    outputCode: '<input type="text" autofocus name="autofocusField">',
  },
  {
    id: 51,
    title: "Autocomplete",
    description:"Enables or disables browser autocomplete Use: When you don't want the browser to suggest saved inputs (e.g., in sensitive forms)",
    inputCode:'<input type="email" autocomplete="off" name="emailNoAutocomplete">',
    outputCode:'<input type="email" autocomplete="off" name="emailNoAutocomplete">',
  },
  {
    id: 52,
    title: "Semantic Layout",
    description: "",
    inputCode:'<header>\r\n  <h1>Website Title</h1>\r\n  <nav>\r\n    <ul>\r\n      <li><a href="#">Home</a></li>\r\n      <li><a href="#">About</a></li>\r\n      <li><a href="#">Contact</a></li>\r\n    </ul>\r\n  </nav>\r\n</header>\r\n\r\n\r\n<main>\r\n  <section>\r\n    <h2>Section Title</h2>\r\n    <article>\r\n      <h3>Article Title</h3>\r\n      <p>Article content...</p>\r\n      <figure>\r\n        <img src="https://picsum.photos/100" alt="Description">\r\n        <figcaption>Figure caption</figcaption>\r\n      </figure>\r\n    </article>\r\n  </section>\r\n \r\n  <aside>\r\n    <h3>Related Information</h3>\r\n    <p>Sidebar content...</p>\r\n  </aside>\r\n</main>\r\n\r\n\r\n<footer>\r\n  <p>&copy; 2025 Your Website</p>\r\n</footer>',
    outputCode:'<header>\r\n  <h1>Website Title</h1>\r\n  <nav>\r\n    <ul>\r\n      <li><a href="#">Home</a></li>\r\n      <li><a href="#">About</a></li>\r\n      <li><a href="#">Contact</a></li>\r\n    </ul>\r\n  </nav>\r\n</header>\r\n\r\n\r\n<main>\r\n  <section>\r\n    <h2>Section Title</h2>\r\n    <article>\r\n      <h3>Article Title</h3>\r\n      <p>Article content...</p>\r\n      <figure>\r\n        <img src="https://picsum.photos/100" alt="Description">\r\n        <figcaption>Figure caption</figcaption>\r\n      </figure>\r\n    </article>\r\n  </section>\r\n \r\n  <aside>\r\n    <h3>Related Information</h3>\r\n    <p>Sidebar content...</p>\r\n  </aside>\r\n</main>\r\n\r\n\r\n<footer>\r\n  <p>&copy; 2025 Your Website</p>\r\n</footer>',
  },
  {
    id: 53,
    title: "Audio",
    description: "",
    inputCode:'<audio controls>\r\n        <source src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" type="audio/mpeg">\r\n        Your browser does not support the audio element.\r\n </audio>',
    outputCode:'<audio controls>\r\n        <source src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" type="audio/mpeg">\r\n        Your browser does not support the audio element.\r\n </audio>',
  },
  {
    id: 54,
    title: "Video",
    description: "",
    inputCode:'<video width="320" height="240" controls>\r\n        <source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">\r\n        <source src="https://www.w3schools.com/html/mov_bbb.ogg" type="video/ogg">\r\n        Your browser does not support the video tag.\r\n</video>',
    outputCode:'<video width="320" height="240" controls>\r\n        <source src="https://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">\r\n        <source src="https://www.w3schools.com/html/mov_bbb.ogg" type="video/ogg">\r\n        Your browser does not support the video tag.\r\n</video>',
  },
  {
    id: 55,
    title: "Track (for Subtitles/Captions)",
    description: "",
    inputCode:'<video width="640" height="360" controls>\r\n    <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4">\r\n    <track src="subtitles_en.vtt" kind="subtitles" srclang="en" label="English" default>\r\n    <track src="subtitles_es.vtt" kind="subtitles" srclang="es" label="Spanish">\r\n    Your browser does not support the video tag.\r\n</video>',
    outputCode:'<video width="640" height="360" controls>\r\n    <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4">\r\n    <track src="subtitles_en.vtt" kind="subtitles" srclang="en" label="English" default>\r\n    <track src="subtitles_es.vtt" kind="subtitles" srclang="es" label="Spanish">\r\n    Your browser does not support the video tag.\r\n</video>',
  },
  {
    id: 56,
    title: "Iframes",
    description: "",
    inputCode:'<iframe src="https://www.youtube.com/embed/jNQXAC9IVRw?si=hg83T0hdb1JCNLbb" width="500" height="300"></iframe>',
    outputCode:'<iframe src="https://www.youtube.com/embed/jNQXAC9IVRw?si=hg83T0hdb1JCNLbb" width="500" height="300"></iframe>',
  },
  {
    id: 57,
    title: "Character Entities",
    description:"HTML character entities are used to display reserved characters or characters that cannot be easily typed.",
    inputCode:"&lt;       <!-- < (less than) -->\r\n&gt;       <!-- > (greater than) -->\r\n&amp;      <!-- & (ampersand) -->\r\n&quot;     <!-- \" (quotation mark) -->\r\n&apos;     <!-- ' (apostrophe) -->\r\n&copy;     <!-- \xA9 (copyright) -->\r\n&reg;      <!-- \xAE (registered trademark) -->\r\n&trade;    <!-- \u2122 (trademark) -->\r\n&nbsp;     <!-- Non-breaking space -->\r\n&mdash;    <!-- \u2014 (em dash) -->\r\n&ndash;    <!-- \u2013 (en dash) -->\r\n&rarr;     <!-- \u2192 (right arrow) -->\r\n&larr;     <!-- \u2190 (left arrow) -->\r\n&euro;     <!-- \u20AC (euro) -->\r\n&pound;    <!-- \xA3 (pound) -->\r\n&yen;      <!-- \xA5 (yen) -->\r\n&cent;     <!-- \xA2 (cent) -->\r\n&deg;      <!-- \xB0 (degree) -->",
    outputCode:"&lt;       <!-- < (less than) -->\r\n&gt;       <!-- > (greater than) -->\r\n&amp;      <!-- & (ampersand) -->\r\n&quot;     <!-- \" (quotation mark) -->\r\n&apos;     <!-- ' (apostrophe) -->\r\n&copy;     <!-- \xA9 (copyright) -->\r\n&reg;      <!-- \xAE (registered trademark) -->\r\n&trade;    <!-- \u2122 (trademark) -->\r\n&nbsp;     <!-- Non-breaking space -->\r\n&mdash;    <!-- \u2014 (em dash) -->\r\n&ndash;    <!-- \u2013 (en dash) -->\r\n&rarr;     <!-- \u2192 (right arrow) -->\r\n&larr;     <!-- \u2190 (left arrow) -->\r\n&euro;     <!-- \u20AC (euro) -->\r\n&pound;    <!-- \xA3 (pound) -->\r\n&yen;      <!-- \xA5 (yen) -->\r\n&cent;     <!-- \xA2 (cent) -->\r\n&deg;      <!-- \xB0 (degree) -->",
  },
  {
    id: 58,
    title: "Geolocation",
    description: "",
    inputCode:'<button onclick="getLocation()">Get Location</button>\r\n<p id="demo"></p>\r\n\r\n\r\n<script>\r\nfunction getLocation() {\r\n  if (navigator.geolocation) {\r\n    navigator.geolocation.getCurrentPosition(showPosition);\r\n  } else {\r\n    document.getElementById("demo").innerHTML = "Geolocation is not supported by this browser.";\r\n  }\r\n}\r\n\r\n\r\nfunction showPosition(position) {\r\n  document.getElementById("demo").innerHTML = "Latitude: " + position.coords.latitude +\r\n  "<br>Longitude: " + position.coords.longitude;\r\n}\r\n</script>',
    outputCode:'<h2>Geolocation</h2>\r\n<button onclick="getLocation()">Get Location</button>\r\n<p id="demo"></p>',
  },
  {
    id: 59,
    title: "Drag and Drop",
    description:"This allows you to drag an image, text, or box and drop it somewhere else.",
    inputCode:'<style>\r\n    #div1 {\r\n        width: 350px;\r\n        height: 350px;\r\n        border: 1px solid black;\r\n        position: relative;\r\n    }\r\n\r\n    #drag1 {\r\n        width: 100px;\r\n        height: 100px;\r\n    }\r\n</style>\r\n\r\n<div id="div1" ondrop="drop(event)" ondragover="allowDrop(event)"></div>\r\n<img id="drag1" src="https://picsum.photos/100" draggable="true" ondragstart="drag(event)">\r\n\r\n\r\n<script>\r\n    function allowDrop(ev) {\r\n        ev.preventDefault();\r\n    }\r\n\r\n\r\n    function drag(ev) {\r\n        ev.dataTransfer.setData("text", ev.target.id);\r\n    }\r\n\r\n\r\n    function drop(ev) {\r\n        ev.preventDefault();\r\n        var data = ev.dataTransfer.getData("text");\r\n        ev.target.appendChild(document.getElementById(data));\r\n    }\r\n</script>',
    outputCode:'<style>\r\n  #div1 {\r\n    width: 350px;\r\n    height: 350px;\r\n    border: 1px solid black;\r\n    position: relative;\r\n    margin-top: 20px;\r\n  }\r\n\r\n  #drag1 {\r\n    width: 100px;\r\n    height: 100px;\r\n    cursor: grab;\r\n  }\r\n</style>\r\n\r\n<!-- Drag and Drop -->\r\n<h2>Drag and Drop</h2>\r\n<div id="div1" ondrop="drop(event)" ondragover="allowDrop(event)"></div>\r\n<img id="drag1" src="https://picsum.photos/100" draggable="true" ondragstart="drag(event)" />',
  },
  {
    id: 60,
    title: "Web Storage",
    description: "",
    inputCode:'<button onclick="storeData()">Store Data</button>\r\n<button onclick="retrieveData()">Retrieve Data</button>\r\n\r\n<p id="localStorageResult"></p>\r\n<p id="sessionStorageResult"></p>\r\n\r\n<script>\r\n  // Function to store data in localStorage and sessionStorage\r\n  function storeData() {\r\n    // Storing data\r\n    localStorage.setItem("localKey", "This is local storage data!");\r\n    sessionStorage.setItem("sessionKey", "This is session storage data!");\r\n\r\n    alert("Data stored in localStorage and sessionStorage!");\r\n  }\r\n\r\n  // Function to retrieve data from localStorage and sessionStorage\r\n  function retrieveData() {\r\n    // Retrieving data\r\n    var localValue = localStorage.getItem("localKey");\r\n    var sessionValue = sessionStorage.getItem("sessionKey");\r\n\r\n    // Displaying data\r\n    document.getElementById("localStorageResult").innerText = "Local Storage Data: " + localValue;\r\n    document.getElementById("sessionStorageResult").innerText = "Session Storage Data: " + sessionValue;\r\n  }\r\n</script>',
    outputCode:'<button onclick="storeData()">Store Data</button>\r\n<button onclick="retrieveData()">Retrieve Data</button>\r\n<p id="localStorageResult"></p>\r\n<p id="sessionStorageResult"></p>',
  },
  {
    id: 61,
    title: "Canvas",
    description:"Canvas allows you to draw shapes, lines, graphs, and even animations inside a <canvas> box.",
    inputCode:'<canvas id="myCanvas" width="200" height="100"></canvas>\r\n\r\n<script>\r\n  var c = document.getElementById("myCanvas");\r\n  var ctx = c.getContext("2d");\r\n  ctx.fillStyle = "#FF0000";\r\n  ctx.fillRect(0, 0, 150, 75);\r\n</script>',
    outputCode:'<canvas id="myCanvas" width="200" height="100" style="background-color:red;"></canvas>',
  },
];

window.notes = notes; 